import type { AvatarV5Config } from "@/components/avatar-v5-production/config/avatar-v5-types";

export const defaultAvatarV5Config: AvatarV5Config = {
  version: 6,
  renderer: "modular-gltf",
  assetFamily: "quaternius-universal",
  frameId: "sculpted",
  bodyPresetId: "balanced",
  facePresetId: "balanced",
  eyeShapeId: "balanced",
  earPresetId: "natural",
  skinToneId: "warm-bronze",
  eyeColourId: "brown",
  hairStyleId: "approved-long",
  hairColourId: "espresso",
  facialHairStyleId: "none",
  topStyleId: "fitted-tee",
  topColourId: "modern-ocean",
  bottomStyleId: "straight-trousers",
  bottomColourId: "modern-graphite",
  shoeStyleId: "ranger-boots",
  shoeColourId: "modern-graphite",
  glassesStyleId: "none",
  accessoryIds: [],
};
