import type {
  AccessoryId,
  AvatarOption,
  BottomStyleId,
  EarPresetId,
  ExpressionId,
  EyeShapeId,
  EyebrowStyleId,
  FacePresetId,
  FacialHairStyleId,
  GlassesStyleId,
  HairStyleId,
  JawPresetId,
  MouthPresetId,
  NosePresetId,
  OuterwearStyleId,
  ShoeStyleId,
  TopStyleId,
} from "@/components/avatar-3d/config/avatar-v4-types";

function options<T extends string>(
  values: ReadonlyArray<AvatarOption<T>>,
): ReadonlyArray<AvatarOption<T>> {
  return values;
}

export const avatarV4Catalogue = {
  facePresets: options<FacePresetId>([
    { label: "Balanced oval", value: "balanced-oval" },
    { label: "Soft round", value: "soft-round" },
    { label: "Defined square", value: "defined-square" },
    { label: "Tapered heart", value: "tapered-heart" },
    { label: "Long sculpted", value: "long-sculpted" },
  ]),
  jawPresets: options<JawPresetId>([
    { label: "Soft", value: "soft" },
    { label: "Balanced", value: "balanced" },
    { label: "Defined", value: "defined" },
    { label: "Tapered", value: "tapered" },
    { label: "Broad", value: "broad" },
  ]),
  eyeShapes: options<EyeShapeId>([
    { label: "Almond", value: "almond" },
    { label: "Round", value: "round" },
    { label: "Hooded", value: "hooded" },
    { label: "Lifted", value: "lifted" },
    { label: "Relaxed", value: "relaxed" },
    { label: "Focused", value: "focused" },
  ]),
  eyeColours: [
    { label: "Deep brown", value: "#302019" },
    { label: "Brown", value: "#5e3e2e" },
    { label: "Hazel", value: "#85703c" },
    { label: "Green", value: "#4e7058" },
    { label: "Blue", value: "#4f799b" },
    { label: "Grey", value: "#75828d" },
    { label: "Amber", value: "#9d692d" },
    { label: "Near black", value: "#151515" },
  ],
  eyebrowStyles: options<EyebrowStyleId>([
    { label: "Natural", value: "natural" },
    { label: "Straight", value: "straight" },
    { label: "Arched", value: "arched" },
    { label: "Soft", value: "soft" },
    { label: "Bold", value: "bold" },
  ]),
  nosePresets: options<NosePresetId>([
    { label: "Soft", value: "soft" },
    { label: "Straight", value: "straight" },
    { label: "Rounded", value: "rounded" },
    { label: "Defined", value: "defined" },
    { label: "Compact", value: "compact" },
  ]),
  mouthPresets: options<MouthPresetId>([
    { label: "Neutral", value: "neutral" },
    { label: "Soft smile", value: "soft-smile" },
    { label: "Confident", value: "confident" },
    { label: "Relaxed", value: "relaxed" },
    { label: "Focused", value: "focused" },
    { label: "Friendly", value: "friendly" },
  ]),
  earPresets: options<EarPresetId>([
    { label: "Classic", value: "classic" },
    { label: "Compact", value: "compact" },
    { label: "Rounded", value: "rounded" },
    { label: "Close", value: "close" },
  ]),
  skinTones: [
    { label: "Porcelain", value: "#f2cfb8" },
    { label: "Warm", value: "#e3ad82" },
    { label: "Golden", value: "#c98d61" },
    { label: "Bronze", value: "#a96947" },
    { label: "Deep", value: "#73462f" },
    { label: "Rich", value: "#482a22" },
  ],
  hairStyles: options<HairStyleId>([
    { label: "Textured crop", value: "textured-crop" },
    { label: "Classic side part", value: "side-part" },
    { label: "Medium swept", value: "medium-swept" },
    { label: "Close crop", value: "close-crop" },
    { label: "Layered bob", value: "layered-bob" },
    { label: "Shoulder waves", value: "shoulder-waves" },
    { label: "Tied ponytail", value: "ponytail" },
    { label: "Curly volume", value: "curly-volume" },
  ]),
  hairColours: [
    { label: "Soft black", value: "#171719" },
    { label: "Espresso", value: "#30231f" },
    { label: "Dark brown", value: "#4b3025" },
    { label: "Chestnut", value: "#704329" },
    { label: "Auburn", value: "#813c2b" },
    { label: "Copper", value: "#a35d37" },
    { label: "Dark blonde", value: "#9a7a43" },
    { label: "Blonde", value: "#c2a15f" },
    { label: "Silver", value: "#9297a0" },
    { label: "Platinum", value: "#d7d1c2" },
  ],
  facialHairStyles: options<FacialHairStyleId>([
    { label: "None", value: "none" },
    { label: "Stubble", value: "stubble" },
    { label: "Moustache", value: "moustache" },
    { label: "Goatee", value: "goatee" },
    { label: "Short beard", value: "short-beard" },
  ]),
  topStyles: options<TopStyleId>([
    { label: "Fitted T-shirt", value: "fitted-tee" },
    { label: "Relaxed T-shirt", value: "relaxed-tee" },
    { label: "Oxford shirt", value: "oxford-shirt" },
    { label: "Polo shirt", value: "polo-shirt" },
    { label: "Crew-neck sweater", value: "crew-sweater" },
    { label: "Hoodie", value: "hoodie" },
    { label: "Blazer", value: "blazer" },
    { label: "Bomber jacket", value: "bomber-jacket" },
  ]),
  outerwearStyles: options<OuterwearStyleId>([
    { label: "None", value: "none" },
    { label: "Blazer", value: "blazer" },
    { label: "Bomber", value: "bomber" },
    { label: "Overshirt", value: "overshirt" },
    { label: "Cardigan", value: "cardigan" },
  ]),
  bottomStyles: options<BottomStyleId>([
    { label: "Straight trousers", value: "straight-trousers" },
    { label: "Slim trousers", value: "slim-trousers" },
    { label: "Jeans", value: "jeans" },
    { label: "Relaxed trousers", value: "relaxed-trousers" },
    { label: "Skirt", value: "skirt" },
    { label: "Sports bottoms", value: "sports-bottoms" },
  ]),
  shoeStyles: options<ShoeStyleId>([
    { label: "Trainers", value: "trainers" },
    { label: "Casual shoes", value: "casual-shoes" },
    { label: "Formal shoes", value: "formal-shoes" },
    { label: "Boots", value: "boots" },
    { label: "Sports shoes", value: "sports-shoes" },
  ]),
  glassesStyles: options<GlassesStyleId>([
    { label: "None", value: "none" },
    { label: "Round", value: "round" },
    { label: "Rectangular", value: "rectangular" },
    { label: "Subtle sunglasses", value: "sunglasses" },
  ]),
  accessories: options<AccessoryId>([
    { label: "Small earrings", value: "earrings" },
    { label: "Watch", value: "watch" },
    { label: "Simple necklace", value: "necklace" },
    { label: "Cap", value: "cap" },
    { label: "Beanie", value: "beanie" },
  ]),
  expressions: options<ExpressionId>([
    { label: "Neutral", value: "neutral" },
    { label: "Warm", value: "warm" },
    { label: "Focused", value: "focused" },
    { label: "Confident", value: "confident" },
  ]),
  clothingColours: [
    { label: "Graphite", value: "#25272c" },
    { label: "Midnight", value: "#1c2942" },
    { label: "Cobalt", value: "#315ebc" },
    { label: "Forest", value: "#2f6350" },
    { label: "Clay", value: "#935343" },
    { label: "Sand", value: "#ad8b5e" },
    { label: "Plum", value: "#684868" },
    { label: "Ivory", value: "#ddd9cf" },
  ],
  bottomColours: [
    { label: "Black", value: "#17181b" },
    { label: "Navy", value: "#253351" },
    { label: "Stone", value: "#716c65" },
    { label: "Charcoal", value: "#3d444d" },
    { label: "Olive", value: "#4d5840" },
    { label: "Denim", value: "#3d5974" },
  ],
  shoeColours: [
    { label: "Ink", value: "#17181b" },
    { label: "White", value: "#deddd7" },
    { label: "Brown", value: "#594031" },
    { label: "Navy", value: "#263955" },
    { label: "Stone", value: "#716c65" },
  ],
} as const;
